FROM resin/rpi-raspbian:jessie

RUN apt-get -y update

RUN apt-get -y install build-essential valgrind bsdmainutils curl git-all
RUN apt-get install libjson0 libjson0-dev
RUN apt-get install libfontconfig1
