FROM resin/rpi-raspbian:jessie

RUN apt-get -y update

RUN apt-get -y install build-essential valgrind bsdmainutils curl git-all

COPY ./* ./*

CD  module
RUN make clean
RUN make

Run ./target/test_alog
